baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
    
[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Model"
    url = "/model/"
[[menu.main]]
    name = "More"
    url = "/more/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"

[params]
    customCSS=["/css/app.css"]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png"

    [params.logo]
    url = "/favicon.png"
    width = 50
    height = 50
    alt = "Logo"

