# This is a workflow to automate the dataset creation for 613covid.ca and
# run short-term hospitalization projections

name: Dataset-creation

# Runs everyday at 2:30pm EST/EDT (7:30pm UTC)
on:
  schedule:
    - cron: "30 19 * * *"
  workflow_dispatch:

jobs:
  dataset-creation:
    runs-on: "ubuntu-latest"
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.ACTION_TOKEN }}
      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.1"
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Install libnode-dev
        run: sudo apt-get install libnode-dev
      - name: Install snap version of nodejs
        run: sudo snap install node --classic --channel=14
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies
        run: R -e 'renv::restore()'
      - name: Download variant sheet from Google Drive
        run: curl -L "https://docs.google.com/spreadsheets/d/1jUAWx9_r7CLhh5vtRNNjCRDMX4nEKEx5gvXM_tpsxhE/export?gid=0&format=xlsx" --output "Data/variant_sheet.xlsx" --create-dirs
      - name: Prepare data
        run: Rscript R/dataset_creation.R
      - name: Run short term ww projections 
        run: Rscript R/short_term_ww_projections.R  
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update projections" -a || echo "Nothing to update"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: "master" #optional defaults to master
